FROM python:3.10-slim

COPY --from=ghcr.io/astral-sh/uv:0.7.9 /uv /uvx /bin/

WORKDIR /app

COPY services/worker/pyproject.toml services/worker/uv.lock ./
COPY services/worker/app/. ./app

RUN uv sync --frozen --no-dev

ENV API_URL=http://api:8000
ENV WORKER_HEARTBEAT_INTERVAL_SECONDS=10
ENV WORKER_ID=worker-001

CMD ["uv", "run", "python", "-m", "app.main"]
