"""add notification recipients

Revision ID: 253c66e1b623
Revises: aa039a2c87dd
Create Date: 2026-07-26 12:01:01.987882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '253c66e1b623'
down_revision: Union[str, Sequence[str], None] = 'aa039a2c87dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('notification_recipients', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'notification_recipients')
    # ### end Alembic commands ###
