"""add_job_payload_and_worker_id

Revision ID: b3c7bc14fe3f
Revises: 253c66e1b623
Create Date: 2026-07-26 22:51:55.062112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3c7bc14fe3f'
down_revision: Union[str, Sequence[str], None] = '253c66e1b623'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('payload', sa.JSON(), nullable=True))
    op.add_column('jobs', sa.Column('worker_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'worker_id')
    op.drop_column('jobs', 'payload')
    # ### end Alembic commands ###
